services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: auth
    hostname: auth
    ports:
      - ${PORT}:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - YOCO_WEBHOOK_SECRET=${YOCO_WEBHOOK_SECRET}
      - YOCO_PUBLIC_KEY=${YOCO_PUBLIC_KEY}
      - YOCO_SECRET_KEY=${YOCO_SECRET_KEY}
    networks:
      - main 
    mem_limit: 512m   # Limit container to 512MB of memory
    mem_reservation: 256m  # Soft memory limit (optional)
    cpus: '0.5'  # Limit container to 50% of a single CPU core

networks:
  main:
    external: true
