version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - DB_FILE_NAME=${DB_FILE_NAME}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./local.db:/app/local.db